### ISSUE TITLE
Bot crashes on message cache

### ISSUE THREAD

**Issue by ellitedev** [nekoellie/speenmapbot#22]
Gonna leave this log here to fix later

```
/usr/src/app/node_modules/discord.js/src/client/actions/MessageCreate.js:11

      const existing = channel.messages.cache.get(data.id);

                                        ^

TypeError: Cannot read properties of undefined (reading 'cache')

    at MessageCreateAction.handle (/usr/src/app/node_modules/discord.js/src/client/actions/MessageCreate.js:11:41)

    at module.exports [as MESSAGE_CREATE] (/usr/src/app/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)

    at WebSocketManager.handlePacket (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)

    at WebSocketShard.onPacket (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)

    at WebSocketShard.onMessage (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)

    at WebSocket.onMessage (/usr/src/app/node_modules/ws/lib/event-target.js:132:16)

    at WebSocket.emit (node:events:514:28)

    at Receiver.receiverOnMessage (/usr/src/app/node_modules/ws/lib/websocket.js:1068:20)

    at Receiver.emit (node:events:514:28)

    at Receiver.dataMessage (/usr/src/app/node_modules/ws/lib/receiver.js:517:14)
```

**Comment by ellitedev** [comment]
fixed in https://github.com/ellitedev/speenmapbot/commit/91ff181b48d6b03264b62bf56b39fe703dbfe1c0
